version: '3.8'
services:
  postgres:
    build: .
    container_name: mypostgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword

volumes:
  postgres_data: